In [ ]:
import json
import spacy
import pandas as pd
import tensorflow as tf

In [ ]:
data = []
with open("/content/drive/MyDrive/ML_Summer2023/NLP/All_Beauty.jsonl", "r") as f:
    for line in f:
        data.append(json.loads(line))

In [ ]:
data

[{'rating': 5.0,
  'title': 'Such a lovely scent but not overpowering.',
  'text': "This spray is really nice. It smells really good, goes on really fine, and does the trick. I will say it feels like you need a lot of it though to get the texture I want. I have a lot of hair, medium thickness. I am comparing to other brands with yucky chemicals so I'm gonna stick with this. Try it!",
  'images': [],
  'asin': 'B00YQ6X8EO',
  'parent_asin': 'B00YQ6X8EO',
  'user_id': 'AGKHLEW2SOWHNMFQIJGBECAF7INQ',
  'timestamp': 1588687728923,
  'helpful_vote': 0,
  'verified_purchase': True},
 {'rating': 4.0,
  'title': 'Works great but smells a little weird.',
  'text': 'This product does what I need it to do, I just wish it was odorless or had a soft coconut smell. Having my head smell like an orange coffee is offputting. (granted, I did know the smell was described but I was hoping it would be light)',
  'images': [],
  'asin': 'B081TJ8YS3',
  'parent_asin': 'B081TJ8YS3',
  'user_id': 'AGKHLEW2SOWH

In [ ]:
data1 = [{'title': item['title'], 'text': item['text'], 'helpful_vote': item['helpful_vote'], 'verified_purchase': item['verified_purchase'], 'rating': item['rating']} for item in data]

In [ ]:
data1

[{'title': 'Such a lovely scent but not overpowering.',
  'text': "This spray is really nice. It smells really good, goes on really fine, and does the trick. I will say it feels like you need a lot of it though to get the texture I want. I have a lot of hair, medium thickness. I am comparing to other brands with yucky chemicals so I'm gonna stick with this. Try it!",
  'helpful_vote': 0,
  'verified_purchase': True,
  'rating': 5.0},
 {'title': 'Works great but smells a little weird.',
  'text': 'This product does what I need it to do, I just wish it was odorless or had a soft coconut smell. Having my head smell like an orange coffee is offputting. (granted, I did know the smell was described but I was hoping it would be light)',
  'helpful_vote': 1,
  'verified_purchase': True,
  'rating': 4.0},
 {'title': 'Yes!',
  'text': 'Smells good, feels great!',
  'helpful_vote': 2,
  'verified_purchase': True,
  'rating': 5.0},
 {'title': 'Synthetic feeling',
  'text': 'Felt synthetic',
  'hel

In [ ]:

df = pd.DataFrame(data1).sample(10000)
df


title  \
194580  Really good brush for the price and it arrived...   
486369                                 Needs improvement!   
684758                                        Three Stars   
40172                                        Great brush!   
519600  These are fantastic. A client brought them to ...   
...                                                   ...   
299369                                            Buy it.   
262203             Smells great, but doesnt cool you down   
280810                           Great product and price.   
322979                        Not for me but good quality   
664269                                         Kidd Rocks   

                                                     text  helpful_vote  \
194580  Really good brush for the price and it arrived...             0   
486369  Could work better...might have been old 🤷🏽‍♀️🤷...             0   
684758  This product is not comfortable. It has an akw...             0   
40172   Great wet hair brush. I recommend them for chi...             0   
519600  These are fantastic. A client brought them to ...             1   
...                                                   ...           ...   
299369                                    Love love love.             0   
262203            Smells great, but doesn't cool you down             1   
280810  This little tool is amazing! Does everything i...             0   
322979  I purchased this hoping I could use it for a h...             0   
664269  best triggers ever<br />buy kidd<br />buy kidd...             0   

        verified_purchase  rating  
194580               True     4.0  
486369               True     5.0  
684758               True     3.0  
40172                True     5.0  
519600               True     5.0  
...                   ...     ...  
299369               True     5.0  
262203               True     3.0  
280810               True     5.0  
322979               True     4.0  
664269               True     5.0  

[4000 rows x 5 columns]

In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
import re

def remove_special_chars(text):

    cleaned_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return cleaned_text

df['title'] = df['title'].apply(remove_special_chars)
df['text'] = df['text'].apply(remove_special_chars)

In [ ]:
df

title  \
194580  Really good brush for the price and it arrived...   
486369                                  Needs improvement   
684758                                        Three Stars   
40172                                         Great brush   
519600  These are fantastic A client brought them to u...   
...                                                   ...   
299369                                             Buy it   
262203              Smells great but doesnt cool you down   
280810                            Great product and price   
322979                        Not for me but good quality   
664269                                         Kidd Rocks   

                                                     text  helpful_vote  \
194580  Really good brush for the price and it arrived...             0   
486369              Could work bettermight have been old              0   
684758  This product is not comfortable It has an akwa...             0   
40172   Great wet hair brush I recommend them for chil...             0   
519600  These are fantastic A client brought them to u...             1   
...                                                   ...           ...   
299369                                     Love love love             0   
262203              Smells great but doesnt cool you down             1   
280810  This little tool is amazing Does everything it...             0   
322979  I purchased this hoping I could use it for a h...             0   
664269  best triggers everbr buy kiddbr buy kiddbr don...             0   

        verified_purchase  rating  
194580               True     4.0  
486369               True     5.0  
684758               True     3.0  
40172                True     5.0  
519600               True     5.0  
...                   ...     ...  
299369               True     5.0  
262203               True     3.0  
280810               True     5.0  
322979               True     4.0  
664269               True     5.0  

[4000 rows x 5 columns]

In [ ]:
default_stop_words = nlp.Defaults.stop_words
custom_stop_words = default_stop_words.copy()
custom_stop_words.remove('not')
def preprocess(text):
  doc = nlp(text)
  tokens=[token.text.lower() for token in doc]
  tokens = [token.text for token in doc if not token.is_stop and token.text.lower() not in custom_stop_words]
  tokens = [token.lemma_ for token in doc]

  cleaned_text = ' '.join(tokens)
  return cleaned_text



In [ ]:
df['text']=df['text'].apply(preprocess)

In [ ]:
df['title']=df['title'].apply(preprocess)

In [ ]:
df

title  \
194580  really good brush for the price and it arrive ...   
486369                                   need improvement   
684758                                         three star   
40172                                         great brush   
519600  these be fantastic a client bring they to use ...   
...                                                   ...   
299369                                             buy it   
262203               smell great but do not cool you down   
280810                            great product and price   
322979                         not for I but good quality   
664269                                         Kidd Rocks   

                                                     text  helpful_vote  \
194580  really good brush for the price and it arrive ...             0   
486369                 could work bettermight have be old             0   
684758  this product be not comfortable it have an akw...             0   
40172   great wet hair brush I recommend they for chil...             0   
519600  these be fantastic a client bring they to use ...             1   
...                                                   ...           ...   
299369                                     love love love             0   
262203               smell great but do not cool you down             1   
280810  this little tool be amazing do everything it n...             0   
322979  I purchase this hope I could use it for a high...             0   
664269  good trigger everbr buy kiddbr buy kiddbr do n...             0   

        verified_purchase  rating  
194580               True     4.0  
486369               True     5.0  
684758               True     3.0  
40172                True     5.0  
519600               True     5.0  
...                   ...     ...  
299369               True     5.0  
262203               True     3.0  
280810               True     5.0  
322979               True     4.0  
664269               True     5.0  

[4000 rows x 5 columns]

In [ ]:
df=df.loc[::,['text','rating']].reset_index()
df=df.loc[::,['text','rating']]
df

text  rating
0     really good brush for the price and it arrive ...       4
1                    could work bettermight have be old       5
2     this product be not comfortable it have an akw...       3
3     great wet hair brush I recommend they for chil...       5
4     these be fantastic a client bring they to use ...       5
...                                                 ...     ...
3995                                     love love love       5
3996               smell great but do not cool you down       3
3997  this little tool be amazing do everything it n...       5
3998  I purchase this hope I could use it for a high...       4
3999  good trigger everbr buy kiddbr buy kiddbr do n...       5

[4000 rows x 2 columns]

In [ ]:
df['rating'] = df['rating'].astype(int)


In [ ]:
!pip install transformers

import numpy as np
from tqdm.auto import tqdm
import tensorflow as tf
from transformers import BertTokenizer

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')


In [ ]:
token = tokenizer.encode_plus(
    df['text'].iloc[0],
    max_length=128,
    truncation=True,
    padding='max_length',
    add_special_tokens=True,
    return_tensors='tf'
)

In [ ]:
token

{'input_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[  101,  1541,  1363,  8415,  1111,  1103,  3945,  1105,  1122,
         6657,  1346,  1190,  5363,   146,  1138,  1129,  1329,  1142,
         1106,  6058,  1139,  1383, 10794,  1105,  1157,  1250,  1198,
         1112,  1632,  1112,  1139,   185,  4907,  1183,  8415,  1121,
        23181, 16426,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0, 

In [ ]:
token.input_ids


<tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[  101,  1541,  1363,  8415,  1111,  1103,  3945,  1105,  1122,
         6657,  1346,  1190,  5363,   146,  1138,  1129,  1329,  1142,
         1106,  6058,  1139,  1383, 10794,  1105,  1157,  1250,  1198,
         1112,  1632,  1112,  1139,   185,  4907,  1183,  8415,  1121,
        23181, 16426,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
X_input_ids = np.zeros((len(df), 128))
X_attn_masks = np.zeros((len(df), 128))
def generate_training_data(df, ids, masks, tokenizer):
    for i, text in tqdm(enumerate(df['text'])):
        tokenized_text = tokenizer.encode_plus(
            text,
            max_length=128,
            truncation=True,
            padding='max_length',
            add_special_tokens=True,
            return_tensors='tf'
        )
        ids[i, :] = tokenized_text.input_ids
        masks[i, :] = tokenized_text.attention_mask
    return ids, masks

In [ ]:
X_input_ids, X_attn_masks = generate_training_data(df, X_input_ids, X_attn_masks, tokenizer)


0it [00:00, ?it/s]

In [ ]:
X_input_ids.shape

(4000, 128)

In [ ]:
X_input_ids

array([[ 101., 1541., 1363., ...,    0.,    0.,    0.],
       [ 101., 1180., 1250., ...,    0.,    0.,    0.],
       [ 101., 1142., 3317., ...,    0.,    0.,    0.],
       ...,
       [ 101., 1142., 1376., ...,    0.,    0.,    0.],
       [ 101.,  146., 4779., ...,    0.,    0.,    0.],
       [ 101., 1363., 9887., ...,    0.,    0.,    0.]])

In [ ]:

labels = np.zeros((len(df), 5))
labels.shape

(4000, 5)

In [ ]:
labels[np.arange(len(df)), df['rating'].values - 1] = 1

In [ ]:
labels

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# creating a data pipeline using tensorflow dataset utility, creates batches of data for easy loading...
dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, labels))
dataset.take(1) # one sample data


<_TakeDataset element_spec=(TensorSpec(shape=(128,), dtype=tf.float64, name=None), TensorSpec(shape=(128,), dtype=tf.float64, name=None), TensorSpec(shape=(5,), dtype=tf.float64, name=None))>

In [ ]:
def SentimentDatasetMapFunction(input_ids, attn_masks, labels):
    return {
        'input_ids': input_ids,
        'attention_mask': attn_masks
    }, labels

In [ ]:
dataset = dataset.map(SentimentDatasetMapFunction) # converting to required format for tensorflow dataset


In [ ]:
dataset.take(1)

<_TakeDataset element_spec=({'input_ids': TensorSpec(shape=(128,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(128,), dtype=tf.float64, name=None)}, TensorSpec(shape=(5,), dtype=tf.float64, name=None))>

In [ ]:
dataset = dataset.shuffle(10000).batch(16, drop_remainder=True) # batch size, drop any left out tensor
p = 0.8
train_size = int((len(df)//16)*p)

train_dataset = dataset.take(train_size)
val_dataset = dataset.skip(train_size)

In [ ]:
# from sklearn.model_selection import train_test_split

# X_input_ids_train, X_input_ids_val, X_attn_masks_train, X_attn_masks_val, labels_train, labels_val = train_test_split(
#     X_input_ids, X_attn_masks, labels, test_size=0.2, random_state=42)

# train_dataset = tf.data.Dataset.from_tensor_slices((X_input_ids_train, X_attn_masks_train, labels_train))
# train_dataset = train_dataset.shuffle(10000).batch(16, drop_remainder=True)

# val_dataset = tf.data.Dataset.from_tensor_slices((X_input_ids_val, X_attn_masks_val, labels_val))
# val_dataset = val_dataset.batch(16, drop_remainder=True)


In [ ]:
val_dataset.take(1)

<_TakeDataset element_spec=({'input_ids': TensorSpec(shape=(16, 128), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(16, 128), dtype=tf.float64, name=None)}, TensorSpec(shape=(16, 5), dtype=tf.float64, name=None))>

In [ ]:
from transformers import TFBertModel


In [ ]:
model = TFBertModel.from_pretrained('bert-base-cased') # bert base model with pretrained weights
# defining 2 input layers for input_ids and attn_masks
input_ids = tf.keras.layers.Input(shape=(128,), name='input_ids', dtype='int32')
attn_masks = tf.keras.layers.Input(shape=(128,), name='attention_mask', dtype='int32')

bert_embds = model.bert(input_ids, attention_mask=attn_masks)[1] # 0 -> activation layer (3D), 1 -> pooled output layer (2D)
intermediate_layer = tf.keras.layers.Dense(512, activation='relu', name='intermediate_layer')(bert_embds)
output_layer = tf.keras.layers.Dense(5, activation='softmax', name='output_layer')(intermediate_layer) # softmax -> calcs probs of classes

sentiment_model = tf.keras.Model(inputs=[input_ids, attn_masks], outputs=output_layer)
sentiment_model.summary()

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_ids (InputLayer)      [(None, 128)]                0         []                            
                                                                                                  
 attention_mask (InputLayer  [(None, 128)]                0         []                            
 )                                                                                                
                                                                                                  
 bert (TFBertMainLayer)      TFBaseModelOutputWithPooli   1083102   ['input_ids[0][0]',           
                             ngAndCrossAttentions(last_   72         'attention_mask[0][0]']      
                             hidden_state=(None, 128, 7                                     

In [ ]:
optim = tf.keras.optimizers.Adam(learning_rate=1e-5)
loss_func = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')
sentiment_model.compile(optimizer=optim, loss=loss_func, metrics=[acc])


In [ ]:

hist = sentiment_model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=30
)

Epoch 1/30
200/200 [==============================] - 91s 452ms/step - loss: 0.6725 - accuracy: 0.7491 - val_loss: 0.5901 - val_accuracy: 0.7700
Epoch 2/30
200/200 [==============================] - 91s 454ms/step - loss: 0.6033 - accuracy: 0.7713 - val_loss: 0.4965 - val_accuracy: 0.8112
Epoch 3/30
200/200 [==============================] - 90s 451ms/step - loss: 0.5172 - accuracy: 0.8159 - val_loss: 0.3647 - val_accuracy: 0.8863
Epoch 4/30
200/200 [==============================] - 90s 450ms/step - loss: 0.4695 - accuracy: 0.8288 - val_loss: 0.3782 - val_accuracy: 0.8662
Epoch 5/30
200/200 [==============================] - 91s 453ms/step - loss: 0.4120 - accuracy: 0.8450 - val_loss: 0.3520 - val_accuracy: 0.8737
Epoch 6/30
200/200 [==============================] - 90s 451ms/step - loss: 0.3535 - accuracy: 0.8712 - val_loss: 0.3205 - val_accuracy: 0.8712
Epoch 7/30
200/200 [==============================] - 90s 450ms/step - loss: 0.3206 - accuracy: 0.8850 - val_loss: 0.2600 - val_ac

In [ ]:
sentiment_model.save('/content/drive/MyDrive/ML_Summer2023/NLP/sentiment_model')


In [ ]:
sentiment_model = tf.keras.models.load_model('/content/drive/MyDrive/ML_Summer2023/NLP/sentiment_model')


In [ ]:
from sklearn.metrics import f1_score

# Assuming sentiment_model.predict returns one-hot encoded predictions
y_pred = sentiment_model.predict(val_dataset)
y_pred_classes = np.argmax(y_pred, axis=1)

y_true = []
for batch in val_dataset:
    labels = batch[1]
    y_true.extend(labels.numpy())

y_true = np.argmax(np.array(y_true), axis=1)

f1 = f1_score(y_true, y_pred_classes, average='weighted')
print("F1 score:", f1)


50/50 [==============================] - 23s 139ms/step
F1 score: 0.3708684942313343


In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

def prepare_data(input_text, tokenizer):
    token = tokenizer.encode_plus(
        input_text,
        max_length=128,
        truncation=True,
        padding='max_length',
        add_special_tokens=True,
        return_tensors='tf'
    )
    return {
        'input_ids': tf.cast(token.input_ids, tf.float64),
        'attention_mask': tf.cast(token.attention_mask, tf.float64)
    }

def make_prediction(model, processed_data, classes=['Negative', 'A bit negative', 'Neutral', 'A bit positive', 'Positive']):
    probs = model.predict(processed_data)[0]
    return classes[np.argmax(probs)]


In [ ]:
input_text = input('Enter movie review here: ')
processed_data = prepare_data(input_text, tokenizer)
result = make_prediction(sentiment_model, processed_data=processed_data)
print(f"Predicted Sentiment: {result}")

Enter movie review here: Perfect not too worst
1/1 [==============================] - 0s 53ms/step
Predicted Sentiment: A bit positive
